# Generated by Django 5.2.6 on 2025-11-10 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heladeria', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cliente',
            table='devices_cliente',
        ),
        migrations.AlterModelTable(
            name='detalleventa',
            table='devices_detalleventa',
        ),
        migrations.AlterModelTable(
            name='producto',
            table='devices_producto',
        ),
        migrations.AlterModelTable(
            name='venta',
            table='devices_venta',
        ),
    ]
