# Generated by Django 5.2.8 on 2025-11-18 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heladeria', '0002_alter_cliente_table_alter_detalleventa_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='rut',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
