# Generated by Django 5.2.8 on 2025-11-18 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heladeria', '0003_cliente_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='rut',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
