# Generated by Django 5.2.6 on 2025-12-14 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heladeria', '0006_categoria_producto_descripcion_producto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='comuna',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='documento_preferido',
            field=models.CharField(choices=[('BOLETA', 'Boleta'), ('FACTURA', 'Factura')], default='BOLETA', max_length=10),
        ),
        migrations.AddField(
            model_name='cliente',
            name='enviar_comprobante_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='idioma_preferido',
            field=models.CharField(choices=[('es', 'Español'), ('en', 'English')], default='es', max_length=5),
        ),
        migrations.AddField(
            model_name='cliente',
            name='pais',
            field=models.CharField(default='Chile', max_length=50),
        ),
        migrations.AddField(
            model_name='cliente',
            name='recibe_promociones',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cliente',
            name='region',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_cliente',
            field=models.CharField(choices=[('PERSONA', 'Persona natural'), ('EMPRESA', 'Empresa')], default='PERSONA', max_length=10),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
